version: "3.8"

services:
  benchmark:
    build: .
    command: sh ./run_benchmark.sh
    working_dir: /app
    stdin_open: true
    tty: true
    network_mode: bridge
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock  # Agrega esto