version: '3'
services:
  benchmark:
    build: .
    volumes:
      - ./solutions:/app/solutions
    command: sh ./run_benchmark.sh
    working_dir: /app
    environment:
      - DOCKER_HOST=tcp://host.docker.internal:2375